// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorwiOCwdMDSRYKFziIxl-pRNU8Y0LJwA',
    appId: '1:180311069698:web:baebac5dbdb7b4f618431b',
    messagingSenderId: '180311069698',
    projectId: 'soft-llama',
    authDomain: 'soft-llama.firebaseapp.com',
    storageBucket: 'soft-llama.appspot.com',
    measurementId: 'G-6GFK1KFVGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzwZSGxtQRpjvqPXZ1qhI9sXQzhn71DU',
    appId: '1:180311069698:android:fdb4350d5d87c5fb18431b',
    messagingSenderId: '180311069698',
    projectId: 'soft-llama',
    storageBucket: 'soft-llama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV44oScaBYw4eaeJJh2mQjL5NrZQYmpQA',
    appId: '1:180311069698:ios:bb5c7f52f7aab5db18431b',
    messagingSenderId: '180311069698',
    projectId: 'soft-llama',
    storageBucket: 'soft-llama.appspot.com',
    iosBundleId: 'com.example.softLlama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV44oScaBYw4eaeJJh2mQjL5NrZQYmpQA',
    appId: '1:180311069698:ios:bb5c7f52f7aab5db18431b',
    messagingSenderId: '180311069698',
    projectId: 'soft-llama',
    storageBucket: 'soft-llama.appspot.com',
    iosBundleId: 'com.example.softLlama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDorwiOCwdMDSRYKFziIxl-pRNU8Y0LJwA',
    appId: '1:180311069698:web:85d23949717ddcf718431b',
    messagingSenderId: '180311069698',
    projectId: 'soft-llama',
    authDomain: 'soft-llama.firebaseapp.com',
    storageBucket: 'soft-llama.appspot.com',
    measurementId: 'G-RK160Z0QZQ',
  );
}
